name: docker workflow
on:
  push
env: 
    IMAGE_NAME: my-custom-image111
    DOCKER_USERNAME: samarth2002
    DOCKER_PASSWORD: Samarthdocker
    CONTAINER_REGISTRY: docker.io
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker build
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: DOCKER LOGIN
      run: echo docker login --username=$DOCKER_USERNAME --password-$DOCKER_PASSWORD

    - name: DOCKER publish
      run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
