name: docker workflow
on:
  push
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        env: 
          DOCKER_USERNAME: samarth2002
          IMAGE_NAME: my-custom-image
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: DOCKER LOGIN
        env:
          DOCKER_USERNAME: samarth2002
          DOCKER_PASSWORD: Samarthdocker
        run: echo docker login --username=$DOCKER_USERNAME --password-$DOCKER_PASSWORD

      - name: DOCKER publish
        env: 
          DOCKER_USERNAME: samarth2002
          CONTAINER_REGISTRY: docker.io
          IMAGE_NAME: my-custom-image
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
