name: Authenticate using GH APP

on: 
  push:
    paths: 
      - .github/workflows/gh-app-auth.yml

jobs:
  check-gh-app:
    runs-on: ubuntu-latest

    steps: 
      - name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_private_key: ${{ secrets.GH_APP_KEY }}
          application_id: ${{ vars.GH_APP_ID }}
          
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          token: ${{ steps.get_token.outputs.token }}
          repository: Samarth-org/GitHub-repo

      - name: Cloning another repo
        run: git clone https://x:${{ steps.get_token_outputs_token }}@github.com/Samarth-org/GitHub-repo 
          
