name: Matrix Stratergy
on: [workflow_dispatch, pull_request]

jobs: 
  job-1:
    strategy:
      matrix:
        version: [1,12,14]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v3.9.1
        with: 
          node-version: ${{ matrix.version }}
        
      
      
