name: matric strategy
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12.x, 15.x]
    runs-on: ${{ matrix.os }}
    steps: 
      - name: setup node version
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node }}
