name: matrix
on: [workflow_dispatch]
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, ubuntu-20.04]
        images: [hello-world, alpine, nginx]
    runs-on: ${{ matrix.os }}
    steps: 
      - name: echo docker info
        run: docker info

      - name: run image on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
      
